import Navigation from '@components/navigation/navigation';
import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.css';

const inter = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={`dark ${inter.className} bg-primaryBg text-fontColor select-none `}>
                <section className="fixed left-0 top-0 right-0">
                    <Navigation />
                </section>
                <main className="pt-24 max-w-7xl mx-auto min-h-screen">{children}</main>
            </body>
        </html>
    );
}
